version: "3"
services:
  api:
    build: .
    image: anima-project
    depends_on:
      - localstack
    ports:
      - "3000:3000"

    container_name: anima_api

    environment:
      AWS_REGION: 'us-west-2'
      AWS_ENDPOINT: 'http://dynamodb_localstack:8000' # localstack container host for dynamodb
      AWS_ACCESS_KEY_ID: 'fake-access-key-id'
      AWS_SECRET_ACCESS_KEY: 'fake-secret-key'

  localstack:
    image: localstack/localstack:latest
    ports:
      - "8080:8080"

    container_name: dynamodb_localstack
    environment:
      SERVICES: dynamodb:8000
      DATA_DIR: '/tmp/localstack/data'